# -*- coding: utf-8 -*-
"""Digits classifier, DNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ive7KT37vxHTwBuHK-hnIcN4kFajk3WV
"""

import tensorflow as tf

from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

mnist.train.images